package se.citerus.dddsample.tracking.core.domain.model.cargo;

import org.apache.commons.lang.StringUtils;
import org.apache.commons.lang.Validate;
import se.citerus.dddsample.tracking.core.domain.patterns.valueobject.ValueObjectSupport;

import java.io.Serializable;

/**
 * Uniquely identifies a particular cargo. Automatically generated by the application.
 */
public final class TrackingId extends ValueObjectSupport<TrackingId> implements Serializable {

  private final String id;

  /**
   * Constructor.
   *
   * @param id Id string.
   */
  public TrackingId(final String id) {
    Validate.notNull(id);
    this.id = id;
  }

  public TrackingId(final long sequenceValue) {
    Validate.isTrue(sequenceValue > 0, "Sequence value must be larger than 0");
    this.id = "C" + StringUtils.leftPad(String.valueOf(sequenceValue), 8, "0");
  }

  /**
   * @return String representation of this tracking id.
   */
  public String stringValue() {
    return id;
  }

  @Override
  public String toString() {
    return id;
  }

  TrackingId() {
    // Needed by Hibernate
    id = null;
  }
  
}
