package se.citerus.dddsample.tracking.core.domain.patterns.entity;

/**
 * Supporting base class for entities.
 *
 * While the Entity interface makes the pattern properties explicit,
 * this class is less general and is suited for this particular application.
 * </p>
 * For example, the private id field is meant for autogenerated, surrogate primary keys.
 */
public abstract class EntitySupport<T extends Entity, ID> implements Entity<T, ID> {

  @SuppressWarnings("UnusedDeclaration")
  private final Long _primaryKey = null;
  
  @Override
  public final boolean sameAs(final T other) {
    return other != null && this.identity().equals(other.identity());
  }

  @Override
  public final int hashCode() {
    return identity().hashCode();
  }

  @SuppressWarnings({"SimplifiableIfStatement", "unchecked"})
  @Override
  public final boolean equals(final Object o) {
    if (this == o) return true;
    // TODO class comparision is too strict for ORM proxies
    if (o == null || !(o instanceof EntitySupport)) return false;
    //if (o == null || getClass() != o.getClass()) return false;

    return sameAs((T) o);
  }

}
