@startuml
skinparam monochrome false
skinparam defaultFontName Courier
skinparam sequenceMessageAlign center

participant "BookingServiceImpl" as bs #lightgreen
participant "CargoRepositoryJPA" as cr #lightblue
participant "Cargo" as c #lightpink
participant "RouteSpecification" as rs #lightpink
participant "Itinerary" as i #lightpink
participant "Delivery" as d #lightpink

[-> bs: assignCargoToRoute(itinerary, trackingId)
activate bs #lightgreen

bs -> cr: find(trackingId)
activate cr #lightblue

bs -> c: assignToRoute(itinerary)
activate c #lightpink

c -> c: routeSpecification()
c -> rs: isSatisfiedBy(itinerary)
activate rs #lightpink
rs --> c: satisfied
deactivate rs

c -> i: legs()
activate i #lightpink
i --> c: legs
deactivate i

c -> c: itinerary = legs

c -> d: updateOnRouting(routeSpecification, itinerary)
activate d #lightpink
d --> c: delivery
deactivate d

c --> bs
deactivate c

bs -> cr: store(cargo)
cr --> bs
deactivate cr

[<-- bs
deactivate bs

@enduml 